[package]
name = "filelock"
version = "0.1.0"
authors = ["sm <s.marx@spa-gmbh.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs2 = "0.4.3"